### ISSUE TITLE
[BUG] Can't run server after updating to v3.1.0

### ISSUE THREAD

**Issue by stevenfukase** [node-saml/passport-saml#620]
Hi.

I updated to v3.1.0 and when I build my project, the following error appears and can't run the server.

```
03:39:26.478Z ERROR aaa: An error occurred, unable to start the server
03:39:26.479Z ERROR aaa: debug_1.default is not a function
  TypeError: debug_1.default is not a function
      at Object.<anonymous> (/workspace/aaa/node_modules/passport-saml/lib/node-saml/saml.js:5:30)
      at Module._compile (internal/modules/cjs/loader.js:1085:14)
      at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Object.nodeDevHook [as .js] (/workspace/aaa/node_modules/node-dev/lib/hook.js:61:7)
      at Module.load (internal/modules/cjs/loader.js:950:32)
      at Function.Module._load (internal/modules/cjs/loader.js:790:14)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at Object.<anonymous> (/workspace/aaa/node_modules/passport-saml/lib/node-saml/index.js:4:16)
      at Module._compile (internal/modules/cjs/loader.js:1085:14)
      at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Object.nodeDevHook [as .js] (/workspace/aaa/node_modules/node-dev/lib/hook.js:61:7)
      at Module.load (internal/modules/cjs/loader.js:950:32)
      at Function.Module._load (internal/modules/cjs/loader.js:790:14)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at Object.<anonymous> (/workspace/aaa/node_modules/passport-saml/lib/passport-saml/index.js:4:21)
      at Module._compile (internal/modules/cjs/loader.js:1085:14)
      at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Object.nodeDevHook [as .js] (/workspace/aaa/node_modules/node-dev/lib/hook.js:61:7)
      at Module.load (internal/modules/cjs/loader.js:950:32)
      at Function.Module._load (internal/modules/cjs/loader.js:790:14)
```

The part where the error is happening is in the package:
(/workspace/aaa/node_modules/passport-saml/lib/node-saml/saml.js:5:30)
```
const debug_1 = require("debug");
const debug = debug_1.default("node-saml");
```
Perhaps there is a mistake how the debug package was imported?

**Environment**
- Node.js version: v14.17.1
- passport-saml version: ^3.1.0

**Comment by cjbarth** [comment]
What was the previous version you had installed?

**Comment by stevenfukase** [comment]
It's 1.0.0

**Comment by cjbarth** [comment]
There are lots of breaking changes between 1.0.0 and 3.1.0. You might want to start with upgrading to 1.5.0 ( `npm install passport-saml@1`), which is the latest in the 1.x series and making sure that works. Then upgrade to `passport-saml@2`, and make sure that works. Then, upgrade to `passport-saml@3`. The release notes along the way might prove helpful to read too.

**Comment by stevenfukase** [comment]
Thanks for the support!
